In [8]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn import preprocessing

In [2]:
def read_json(file):
    reader = pd.read_json(f"Data/{file}.json")
    return reader[['onetsoc_code','element_id', 'scale_id', 'data_value']]

In [3]:
mean_dataset = pd.read_csv("mean_dataset.csv")
final_dataset = pd.read_csv("big_dataset.csv")

In [16]:
le = preprocessing.LabelEncoder()
final_dataset["onetsoc_code"] = le.fit_transform(final_dataset["onetsoc_code"])

In [17]:
final_dataset.isnull().sum()

onetsoc_code    0
2.A.1.a_IM      0
2.A.1.a_LV      0
2.A.1.b_IM      0
2.A.1.b_LV      0
               ..
1.A.4.b.3_LV    1
1.A.4.b.4_IM    1
1.A.4.b.4_LV    1
1.A.4.b.5_IM    1
1.A.4.b.5_LV    1
Length: 323, dtype: int64

In [13]:
mean_dataset.set_index('onetsoc_code')

,2.A.1.a,2.A.1.b,2.A.1.c,2.A.1.d,2.A.1.e,2.A.1.f,2.A.2.a,2.A.2.b,2.A.2.c,2.A.2.d,...,1.A.4.a.3,1.A.4.a.4,1.A.4.a.5,1.A.4.a.6,1.A.4.a.7,1.A.4.b.1,1.A.4.b.2,1.A.4.b.3,1.A.4.b.4,1.A.4.b.5
onetsoc_code,,,,,,,,,,,,,,,,,,,,,
0,4.435,4.500,4.190,4.630,3.435,1.500,4.565,4.375,3.500,4.810,...,1.750,0.500,0.500,1.625,0.500,1.625,2.120,0.500,4.370,4.500
1,4.125,4.000,4.130,4.125,3.065,1.625,4.060,3.625,3.440,3.870,...,1.810,0.500,0.500,1.940,0.500,1.750,1.750,0.620,3.810,3.810
2,3.940,4.000,3.565,4.000,2.440,1.500,3.940,3.560,3.125,4.000,...,2.125,0.940,1.190,1.940,0.880,2.000,2.060,1.060,3.565,3.625
3,3.875,4.120,3.815,4.060,3.125,1.120,4.060,3.685,3.125,3.750,...,2.815,0.500,0.500,1.375,0.500,1.500,1.500,0.500,3.940,3.940
4,4.065,4.000,3.565,4.000,2.935,1.625,4.065,4.000,3.310,4.000,...,2.880,0.500,0.500,1.250,0.500,1.690,1.750,0.500,3.750,3.815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,3.120,3.060,2.940,3.000,2.185,1.565,3.310,2.630,2.315,3.060,...,2.630,1.625,1.690,2.620,2.000,2.815,3.000,1.750,2.815,2.940
938,3.065,3.065,2.875,2.870,2.440,1.440,3.250,2.620,2.380,3.440,...,2.875,1.630,1.880,2.940,2.250,2.875,3.375,1.625,2.880,2.815
939,2.815,2.815,2.370,3.000,1.935,0.620,3.060,2.250,1.630,3.185,...,1.810,1.185,1.625,2.060,1.690,2.000,2.435,1.250,2.875,2.750
940,2.630,2.750,2.565,2.625,0.940,0.500,3.000,2.250,1.190,2.500,...,3.000,2.250,2.190,2.815,2.435,2.630,2.370,2.060,2.940,3.000
941,2.440,2.435,1.870,2.630,1.310,0.620,2.625,1.810,1.190,2.870,...,1.255,1.630,1.565,3.315,2.005,1.440,2.190,0.815,2.440,2.505

In [14]:
kmeans = KMeans(n_clusters=10).fit(mean_dataset)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').